export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const CUSTOMER_LOGIN_SCREEN = 'CUSTOMER_LOGIN_SCREEN';
export const DELIVERY_LOGIN_SCREEN = 'DELIVERY_LOGIN_SCREEN';
export const PRODUCT_DASHBOARD_SCREEN = 'PRODUCT_DASHBOARD_SCREEN';
export const DELIVERY_DASHBOARD_SCREEN = 'DELIVERY_DASHBOARD_SCREEN';
